# Generated by Django 4.2.13 on 2024-08-07 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Publication', '0002_publication_delete_publications'),
        ('Author', '0002_author'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Authors',
        ),
    ]
