# Generated by Django 4.2.14 on 2024-08-05 22:53

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Author', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('date_pub', models.DateField(default=datetime.date.today)),
                ('pub_text', models.CharField(max_length=50, verbose_name='Texto da Publicação')),
                ('pub_title', models.CharField(max_length=30, verbose_name='Título da Publicação')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Author.authors')),
            ],
            options={
                'db_table': 'publicações',
            },
        ),
    ]
