# Generated by Django 4.2.13 on 2024-08-07 22:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Author', '0002_author'),
        ('Publication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_pub', models.DateField(auto_now_add=True, verbose_name='publication date')),
                ('pub_title', models.CharField(max_length=100, verbose_name='publication title')),
                ('pub_text', models.TextField(max_length=255, verbose_name='publications')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Author.author')),
            ],
            options={
                'db_table': 'pubblications',
            },
        ),
        migrations.DeleteModel(
            name='Publications',
        ),
    ]
